phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.2, "unitless"),
            "final_mach": (0.81, "unitless"),
            "mach_bounds": ((0.18, 0.83), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (32000.0, "ft"),
            "altitude_bounds": ((0.0, 34000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((30.0, 45.0), "min"),
        },
        "initial_guesses": {"time": ([0, 44], "min"),
                            "distance": ([0, 250], 'nmi'),
                            "mass": ([130000, 120000], 'lbm')},
    },
    "cruise": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.81, "unitless"),
            "final_mach": (0.81, "unitless"),
            "mach_bounds": ((0.7, 0.84), "unitless"),
            "initial_altitude": (32000.0, "ft"),
            "final_altitude": (34000.0, "ft"),
            "altitude_bounds": ((23000.0, 38000.0), "ft"),
            "throttle_enforcement": "bounded",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            # Absolute estimate start for this phae
            "initial_bounds": ((30.0, 45.0), "min"),
            "duration_bounds": ((60, 450), "min"),  # relative time for this phase
        },
        # first value is initial time absolute, second value is duration / relative
        "initial_guesses": {"time": ([45, 413], "min"),
                            "distance": ([250, 3000], 'nmi'),
                            "mass": ([120000, 105000], 'lbm')},
    },
    "descent": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.81, "unitless"),
            "final_mach": (0.36, "unitless"),
            "mach_bounds": ((0.34, 0.83), "unitless"),
            "initial_altitude": (34000.0, "ft"),
            "final_altitude": (500.0, "ft"),
            "altitude_bounds": ((0.0, 38000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((90, 495), "min"),
            "duration_bounds": ((29.0, 87.0), "min"),
        },
        "initial_guesses": {"time": ([443, 86], "min"),
                            "distance": ([3000, 3500], 'nmi'),
                            "mass": ([105000, 100000], 'lbm')},
    },
    "post_mission": {
        "include_landing": False,
        "target_range": (3500, "nmi"),
    },
}
